version: '3.1'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rmq3"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    labels:
      NAME: "rabbitmq1"
    ports:
      - "5672:5672"
      - "15672:15672"
      
  calculator:
      image: calculator
      container_name: calculator-app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:8080"
      restart: always
      environment:
        - SPRING_RABBITMQ_HOST=rabbitmq
      depends_on:
        - rabbitmq